import { and, desc, eq, sql } from 'drizzle-orm'
import { Activity, AlertTriangle, BarChart3, BookOpen, CalendarDays, CheckSquare2, ClipboardCheck, FileText, GraduationCap, MapPin, Megaphone, MessageSquare, School, Settings2, Users, UserRoundPlus } from 'lucide-react'
import { requireDb } from '@/db'
import { announcements, assessments, assignments, attendanceRecords, calendarEvents, classes, communityPosts, files, grades, notifications, registrationRequests, rules, schoolLocations, siteSettings, subjects, teachingAssignments, teachers, users } from '@/db/schema'
import {
  approveRegistrationAction, assignTeacherAction, bulkGradesAction, createAnnouncementAction, createAssessmentAction, createAssignmentAction, createAttendanceAction,
  createCalendarEventAction, createClassAction, createFileAction, createLocationAction, createNotificationAction, createRuleAction,
  createStudentAction, createSubjectAction, createTeacherAction, deleteContentAction, moderatePostAction, rejectRegistrationAction, sendAnnouncementNotificationAction,
  toggleUserAction, updateSettingAction, upsertGradeAction,
} from './actions'

export const dynamic = 'force-dynamic'

function countQuery(table:any){ return requireDb().select({count:sql<number>`count(*)::int`}).from(table).then(r=>r[0]?.count??0) }
const input=(name:string,label:string,type='text',required=true)=><label className="admin-field"><span>{label}</span><input name={name} type={type} required={required}/></label>
const area=(name:string,label:string,required=true)=><label className="admin-field"><span>{label}</span><textarea name={name} rows={3} required={required}/></label>
const select=(name:string,label:string,options:{value:string;label:string}[],required=true)=><label className="admin-field"><span>{label}</span><select name={name} required={required}><option value="">اختر…</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>
const check=(name:string,label:string,checked=false)=><label className="admin-check"><input name={name} type="checkbox" defaultChecked={checked}/><span>{label}</span></label>

function ActionButton({children}: {children:React.ReactNode}) { return <button className="button button-primary" type="submit">{children}</button> }
function DeleteButton({resource,id}:{resource:string;id:string}) { return <form action={deleteContentAction}><input type="hidden" name="resource" value={resource}/><input type="hidden" name="id" value={id}/><button className="admin-danger" type="submit">حذف</button></form> }
function ToggleButton({id,active}:{id:string;active:boolean}) { return <form action={toggleUserAction}><input type="hidden" name="id" value={id}/><button className="admin-small-button" type="submit">{active?'تعطيل':'تفعيل'}</button></form> }

export default async function AdminPage(){
  const db=requireDb()
  const [counts, recentUsers, classesRows, subjectsRows, teachersRows, studentsRows, assessmentsRows, announcementsRows, assignmentsRows, eventsRows, ruleRows, locationRows, fileRows, notificationRows, postsRows, settingsRows, pendingRegistrationsRows] = await Promise.all([
    Promise.all([countQuery(users),countQuery(teachers),countRole('student'),countQuery(classes),countQuery(subjects),countQuery(assessments),countQuery(grades),countQuery(assignments),countQuery(announcements),countQuery(calendarEvents),countQuery(files),countQuery(notifications),countQuery(communityPosts),countQuery(rules),countQuery(attendanceRecords),countQuery(schoolLocations)]),
    db.select({id:users.id,name:users.fullNameAr,email:users.email,role:users.role,active:users.isActive}).from(users).orderBy(desc(users.createdAt)).limit(16),
    db.select().from(classes).orderBy(desc(classes.createdAt)).limit(25),
    db.select().from(subjects).orderBy(desc(subjects.createdAt)).limit(25),
    db.select({id:teachers.id,userId:teachers.userId,code:teachers.employeeCode,department:teachers.department,name:users.fullNameAr,email:users.email,active:users.isActive}).from(teachers).innerJoin(users,eq(users.id,teachers.userId)).orderBy(desc(teachers.createdAt)).limit(25),
    db.select({id:users.id,name:users.fullNameAr,email:users.email,studentNumber:users.studentNumber,classId:users.classId,active:users.isActive}).from(users).where(eq(users.role,'student')).orderBy(desc(users.createdAt)).limit(25),
    db.select({id:assessments.id,title:assessments.titleAr,maxScore:assessments.maxScore,examOrder:assessments.examOrder,subject:subjects.nameAr,className:classes.nameAr,published:assessments.published}).from(assessments).leftJoin(subjects,eq(subjects.id,assessments.subjectId)).leftJoin(classes,eq(classes.id,assessments.classId)).orderBy(desc(assessments.createdAt)).limit(20),
    db.select({id:announcements.id,title:announcements.titleAr,published:announcements.published,createdAt:announcements.createdAt}).from(announcements).orderBy(desc(announcements.createdAt)).limit(15),
    db.select({id:assignments.id,title:assignments.titleAr,dueAt:assignments.dueAt,published:assignments.published,subject:subjects.nameAr,className:classes.nameAr}).from(assignments).leftJoin(subjects,eq(subjects.id,assignments.subjectId)).leftJoin(classes,eq(classes.id,assignments.classId)).orderBy(desc(assignments.createdAt)).limit(15),
    db.select({id:calendarEvents.id,title:calendarEvents.titleAr,startsAt:calendarEvents.startsAt,location:calendarEvents.location}).from(calendarEvents).orderBy(desc(calendarEvents.startsAt)).limit(15),
    db.select({id:rules.id,title:rules.titleAr,published:rules.published,sortOrder:rules.sortOrder}).from(rules).orderBy(rules.sortOrder).limit(15),
    db.select().from(schoolLocations).orderBy(desc(schoolLocations.createdAt)).limit(15),
    db.select({id:files.id,name:files.name,url:files.url,visibility:files.visibility,size:files.sizeBytes}).from(files).orderBy(desc(files.createdAt)).limit(15),
    db.select({id:notifications.id,title:notifications.titleAr,userId:notifications.userId,createdAt:notifications.createdAt}).from(notifications).orderBy(desc(notifications.createdAt)).limit(15),
    db.select({id:communityPosts.id,body:communityPosts.body,published:communityPosts.published,pinned:communityPosts.pinned,author:users.fullNameAr}).from(communityPosts).innerJoin(users,eq(users.id,communityPosts.authorId)).orderBy(desc(communityPosts.createdAt)).limit(15),
    db.select().from(siteSettings).orderBy(siteSettings.key).limit(30),
    db.select({
      id: registrationRequests.id, email: registrationRequests.email, googleName: registrationRequests.googleName,
      fullName: registrationRequests.fullName, birthDate: registrationRequests.birthDate, phone: registrationRequests.phone,
      createdAt: registrationRequests.createdAt, className: classes.nameAr, section: classes.section,
    }).from(registrationRequests).leftJoin(classes, eq(classes.id, registrationRequests.classId)).where(eq(registrationRequests.status, 'pending')).orderBy(desc(registrationRequests.createdAt)).limit(50),
  ])
  const usersCount=counts[0], teachersCount=counts[1], studentsCount=counts[2], classesCount=counts[3], subjectsCount=counts[4], assessmentsCount=counts[5], gradesCount=counts[6], assignmentsCount=counts[7], announcementsCount=counts[8], eventsCount=counts[9], filesCount=counts[10], notificationsCount=counts[11], postsCount=counts[12], rulesCount=counts[13], attendanceCount=counts[14], locationsCount=counts[15]
  const teacherOptions=teachersRows.map(t=>({value:t.id,label:`${t.name} · ${t.code}`}))
  const studentOptions=studentsRows.map(s=>({value:s.id,label:`${s.name} · ${s.studentNumber??s.email}`}))
  const classOptions=classesRows.map(c=>({value:c.id,label:`${c.nameAr} · ${c.gradeLevel}`}))
  const subjectOptions=subjectsRows.map(s=>({value:s.id,label:`${s.nameAr} (${s.code})`}))
  const assessmentOptions=assessmentsRows.map(a=>({value:a.id,label:`${a.title} · ${a.subject??''}`}))
  return <div className="admin-page">
    <header className="admin-header"><div><span className="eyebrow">ADMIN CONTROL CENTER</span><h1>لوحة إدارة المدرسة</h1><p>كل البيانات التشغيلية للمنصة من مكان واحد.</p></div><div className="admin-health"><Activity size={18}/><span>قاعدة البيانات: <strong>{process.env.DATABASE_URL?'متصلة':'غير مهيأة'}</strong></span></div></header>
    <section className="admin-stats">{[
      ['طلبات التسجيل',pendingRegistrationsRows.length,ClipboardCheck],['المستخدمون',usersCount,Users],['المدرسون',teachersCount,GraduationCap],['الطلاب',studentsCount,UserRoundPlus],['الصفوف',classesCount,School],['المواد',subjectsCount,BookOpen],['الدرجات',gradesCount,BarChart3],['الواجبات',assignmentsCount,CheckSquare2],['التبليغات',announcementsCount,Megaphone],['التقويم',eventsCount,CalendarDays],['الملفات',filesCount,FileText],['الإشعارات',notificationsCount,AlertTriangle],['المجتمع',postsCount,MessageSquare],['القواعد',rulesCount,Settings2],['الحضور',attendanceCount,Activity],['المواقع',locationsCount,MapPin]
    ].map(([label,value,Icon])=><div className="admin-stat" key={String(label)}><span>{label as string}</span><strong>{String(value)}</strong></div>)}</section>

    <div className="admin-grid">
      <details className="admin-panel" open><summary><ClipboardCheck size={18}/> طلبات التسجيل — بانتظار الموافقة</summary><div className="admin-panel-body">
        {pendingRegistrationsRows.length===0 ? <p className="admin-empty">لا توجد طلبات تسجيل معلقة.</p> : <div className="registration-admin-list">{pendingRegistrationsRows.map(r=><div className="registration-admin-card" key={r.id}><div className="registration-admin-main"><div className="registration-admin-head"><div><strong>{r.fullName || r.googleName || 'طالب جديد'}</strong><span>{r.email}</span></div><span className="security-pill">قيد المراجعة</span></div><div className="registration-admin-meta"><span>الهاتف: <b dir="ltr">{r.phone}</b></span><span>الميلاد: <b>{r.birthDate}</b></span><span>الصف: <b>{r.className || '—'}{r.section ? ` · ${r.section}` : ''}</b></span><span>أُرسل: <b>{r.createdAt.toLocaleString('ar-IQ')}</b></span></div></div><div className="registration-admin-actions"><form action={approveRegistrationAction}><input type="hidden" name="id" value={r.id}/><button className="button button-primary" type="submit">موافقة وإنشاء الحساب</button></form><form action={rejectRegistrationAction} className="registration-reject-form"><input type="hidden" name="id" value={r.id}/><input name="reason" placeholder="سبب الرفض (اختياري)"/><button className="admin-danger" type="submit">رفض الطلب</button></form></div></div>)}</div>}
      </div></details>

      <details className="admin-panel" open><summary><UserRoundPlus size={18}/> الحسابات والكوادر</summary><div className="admin-panel-body admin-two-col">
        <form action={createTeacherAction} className="admin-form"><h3>إضافة مدرس</h3><div className="admin-form-grid">{input('fullNameAr','الاسم بالعربي')}{input('fullNameEn','الاسم بالإنكليزي')}{input('email','البريد','email')}{input('password','كلمة المرور','password')}{input('code','رمز الموظف')}{input('department','القسم', 'text', false)}{input('titleAr','المسمى الوظيفي بالعربي','text',false)}{input('titleEn','المسمى الوظيفي بالإنكليزي','text',false)}{input('phone','الهاتف','tel',false)}</div><ActionButton>إنشاء حساب مدرس</ActionButton></form>
        <form action={createStudentAction} className="admin-form"><h3>إضافة طالب</h3><div className="admin-form-grid">{input('fullNameAr','الاسم بالعربي')}{input('fullNameEn','الاسم بالإنكليزي')}{input('email','البريد','email')}{input('password','كلمة المرور','password')}{input('code','الرقم الطلابي')}{input('phone','الهاتف','tel',false)}{select('classId','الصف',classOptions)}</div><ActionButton>إنشاء حساب طالب</ActionButton></form>
      </div></details>

      <details className="admin-panel"><summary><School size={18}/> الصفوف والمواد</summary><div className="admin-panel-body admin-two-col">
        <form action={createClassAction} className="admin-form"><h3>صف جديد</h3><div className="admin-form-grid">{input('nameAr','اسم الصف بالعربي')}{input('nameEn','اسم الصف بالإنكليزي')}{input('gradeLevel','المرحلة','number')}{input('section','الشعبة','text',false)}{input('room','القاعة','text',false)}{input('capacity','السعة','number',false)}</div><ActionButton>إضافة الصف</ActionButton></form>
        <form action={createSubjectAction} className="admin-form"><h3>مادة جديدة</h3><div className="admin-form-grid">{input('code','كود المادة')}{input('nameAr','اسم المادة بالعربي')}{input('nameEn','اسم المادة بالإنكليزي')}{input('color','لون المادة','text',false)}</div><ActionButton>إضافة المادة</ActionButton></form>
      </div><div className="admin-list">{classesRows.map(c=><div className="admin-list-row" key={c.id}><div><strong>{c.nameAr}</strong><span>{c.nameEn} · المرحلة {c.gradeLevel} · {c.section??'بدون شعبة'}</span></div><DeleteButton resource="class" id={c.id}/></div>)}{subjectsRows.map(s=><div className="admin-list-row" key={s.id}><div><strong>{s.nameAr}</strong><span>{s.nameEn} · {s.code}</span></div><DeleteButton resource="subject" id={s.id}/></div>)}</div></details>

      <details className="admin-panel"><summary><GraduationCap size={18}/> توزيع المدرسين</summary><div className="admin-panel-body"><form action={assignTeacherAction} className="admin-form"><div className="admin-form-grid">{select('teacherId','المدرس',teacherOptions)}{select('subjectId','المادة',subjectOptions)}{select('classId','الصف',classOptions)}{input('academicYear','السنة الدراسية')}{input('semester','الفصل الدراسي')}</div><ActionButton>ربط المدرس بالمادة والصف</ActionButton></form><div className="admin-list">{recentUsers.filter(u=>u.role!=='admin').map(u=><div className="admin-list-row" key={u.id}><div><strong>{u.name}</strong><span>{u.email} · {u.role}</span></div><ToggleButton id={u.id} active={u.active}/></div>)}</div></div></details>

      <details className="admin-panel"><summary><BarChart3 size={18}/> الاختبارات والدرجات</summary><div className="admin-panel-body admin-two-col">
        <form action={createAssessmentAction} className="admin-form"><h3>تعريف اختبار/تقييم</h3><div className="admin-form-grid">{input('titleAr','العنوان بالعربي')}{input('titleEn','العنوان بالإنكليزي')}{select('type','نوع التقييم',[{value:'exam',label:'اختبار'},{value:'quiz',label:'اختبار قصير'},{value:'assignment',label:'واجب'},{value:'project',label:'مشروع'},{value:'participation',label:'مشاركة'}])}{select('subjectId','المادة',subjectOptions)}{select('classId','الصف',classOptions)}{input('examOrder','ترتيب الامتحان','number',false)}{input('maxScore','الدرجة الكاملة','number')}{input('startsAt','موعد الاختبار','datetime-local',false)}</div>{check('published','نشر النتائج/الاختبار')}<ActionButton>إنشاء التقييم</ActionButton></form>
        <form action={upsertGradeAction} className="admin-form"><h3>إضافة أو تحديث درجة</h3><div className="admin-form-grid">{select('assessmentId','التقييم',assessmentOptions)}{select('studentId','الطالب',studentOptions)}{input('score','الدرجة','number')}{area('feedback','ملاحظة',false)}</div><ActionButton>حفظ الدرجة</ActionButton></form>
        <form action={bulkGradesAction} className="admin-form"><h3>رفع درجات دفعة واحدة</h3><p className="admin-help">كل سطر: <code>student-email,assessment-id,score,feedback</code></p><textarea name="csv" rows={7} placeholder="student@example.com,assessment-uuid,87,ملاحظة" required/><ActionButton>رفع الدرجات</ActionButton></form>
      </div><div className="admin-list">{assessmentsRows.map(a=><div className="admin-list-row" key={a.id}><div><strong>{a.title}</strong><span>{a.subject} · {a.className} · / {a.maxScore} · {a.published?'منشور':'مسودة'}</span></div><DeleteButton resource="assessment" id={a.id}/></div>)}</div></details>

      <details className="admin-panel"><summary><Megaphone size={18}/> الإعلانات والتبليغات</summary><div className="admin-panel-body admin-two-col">
        <form action={createAnnouncementAction} className="admin-form"><h3>إعلان جديد</h3><div className="admin-form-grid">{input('titleAr','العنوان بالعربي')}{input('titleEn','العنوان بالإنكليزي')}{select('audience','الفئة',[{value:'all',label:'الجميع'},{value:'students',label:'الطلاب'},{value:'teachers',label:'المدرسون'},{value:'admins',label:'الإدارة'},{value:'class',label:'صف محدد'}])}{select('classId','الصف',classOptions,false)}{area('bodyAr','النص بالعربي')}{area('bodyEn','النص بالإنكليزي')}</div>{check('published','نشر فورًا')}<ActionButton>نشر الإعلان</ActionButton></form>
        <form action={sendAnnouncementNotificationAction} className="admin-form"><h3>إرسال إشعار للجمهور</h3><div className="admin-form-grid">{input('titleAr','عنوان عربي')}{input('titleEn','عنوان إنكليزي')}{select('audience','الجمهور',[{value:'all',label:'الجميع'},{value:'students',label:'الطلاب'},{value:'teachers',label:'المدرسون'}])}{area('bodyAr','النص العربي')}{area('bodyEn','النص الإنكليزي')}</div><ActionButton>إرسال الإشعار</ActionButton></form>
      </div><div className="admin-list">{announcementsRows.map(a=><div className="admin-list-row" key={a.id}><div><strong>{a.title}</strong><span>{a.published?'منشور':'مسودة'} · {a.createdAt.toLocaleString('ar-IQ')}</span></div><DeleteButton resource="announcement" id={a.id}/></div>)}</div></details>

      <details className="admin-panel"><summary><CheckSquare2 size={18}/> الواجبات والمواعيد</summary><div className="admin-panel-body admin-two-col"><form action={createAssignmentAction} className="admin-form"><h3>واجب جديد</h3><div className="admin-form-grid">{input('titleAr','العنوان بالعربي')}{input('titleEn','العنوان بالإنكليزي')}{select('subjectId','المادة',subjectOptions)}{select('classId','الصف',classOptions)}{select('teacherId','المدرس',teacherOptions,false)}{input('dueAt','آخر موعد','datetime-local')}{input('maxScore','الدرجة الكاملة','number')}</div>{area('descriptionAr','الوصف بالعربي',false)}{area('descriptionEn','الوصف بالإنكليزي',false)}{check('published','نشر الواجب')}<ActionButton>إضافة الواجب</ActionButton></form>
        <form action={createCalendarEventAction} className="admin-form"><h3>حدث تقويمي</h3><div className="admin-form-grid">{input('titleAr','العنوان بالعربي')}{input('titleEn','العنوان بالإنكليزي')}{input('startsAt','البداية','datetime-local')}{input('endsAt','النهاية','datetime-local',false)}{input('location','المكان','text',false)}{select('classId','الصف',classOptions,false)}{select('subjectId','المادة',subjectOptions,false)}</div>{area('descriptionAr','الوصف بالعربي',false)}{area('descriptionEn','الوصف بالإنكليزي',false)}<ActionButton>إضافة إلى التقويم</ActionButton></form></div><div className="admin-list">{assignmentsRows.map(a=><div className="admin-list-row" key={a.id}><div><strong>{a.title}</strong><span>{a.subject} · {a.className} · استحقاق {a.dueAt.toLocaleString('ar-IQ')}</span></div><DeleteButton resource="assignment" id={a.id}/></div>)}{eventsRows.map(e=><div className="admin-list-row" key={e.id}><div><strong>{e.title}</strong><span>{e.startsAt.toLocaleString('ar-IQ')} · {e.location??'بدون موقع'}</span></div><DeleteButton resource="event" id={e.id}/></div>)}</div></details>

      <details className="admin-panel"><summary><Settings2 size={18}/> القواعد والمجتمع</summary><div className="admin-panel-body admin-two-col"><form action={createRuleAction} className="admin-form"><h3>قاعدة جديدة</h3><div className="admin-form-grid">{input('titleAr','العنوان بالعربي')}{input('titleEn','العنوان بالإنكليزي')}{input('sortOrder','الترتيب','number')}</div>{area('bodyAr','المحتوى العربي')}{area('bodyEn','المحتوى الإنكليزي')}{check('published','نشر القاعدة',true)}<ActionButton>إضافة القاعدة</ActionButton></form><div className="admin-form"><h3>مراجعة منشورات المجتمع</h3>{postsRows.length===0?<p className="admin-empty">لا توجد منشورات.</p>:postsRows.map(p=><div className="admin-list-row" key={p.id}><div><strong>{p.author}</strong><span>{p.body.slice(0,90)}</span></div><form action={moderatePostAction} className="admin-inline-form"><input type="hidden" name="id" value={p.id}/><input type="hidden" name="published" value={p.published?'on':''}/><input type="hidden" name="pinned" value={p.pinned?'on':''}/><button className="admin-small-button" type="submit">{p.published?'إخفاء':'نشر'}</button></form><DeleteButton resource="post" id={p.id}/></div>)}</div></div></details>

      <details className="admin-panel"><summary><FileText size={18}/> الملفات والتخزين</summary><div className="admin-panel-body"><form action={createFileAction} className="admin-form"><h3>تسجيل ملف مستضاف</h3><div className="admin-form-grid">{input('name','اسم الملف')}{input('url','رابط الملف','url')}{input('mimeType','MIME type','text',false)}{input('sizeBytes','الحجم بالبايت','number',false)}{input('folder','المجلد','text',false)}{select('visibility','الرؤية',[{value:'all',label:'الجميع'},{value:'students',label:'الطلاب'},{value:'teachers',label:'المدرسون'},{value:'admins',label:'الإدارة'}])}{select('ownerId','المالك',studentOptions,false)}</div><ActionButton>حفظ الملف</ActionButton></form><div className="admin-list">{fileRows.map(f=><div className="admin-list-row" key={f.id}><div><strong>{f.name}</strong><span>{f.visibility} · {f.size??0} bytes · {f.url}</span></div><DeleteButton resource="file" id={f.id}/></div>)}</div></div></details>

      <details className="admin-panel"><summary><AlertTriangle size={18}/> الإشعارات والحضور</summary><div className="admin-panel-body admin-two-col"><form action={createNotificationAction} className="admin-form"><h3>إشعار يدوي</h3><div className="admin-form-grid">{select('userId','المستلم',studentOptions,false)}{input('titleAr','العنوان بالعربي')}{input('titleEn','العنوان بالإنكليزي')}</div>{area('bodyAr','النص بالعربي')}{area('bodyEn','النص بالإنكليزي')}<ActionButton>إنشاء إشعار</ActionButton></form><form action={createAttendanceAction} className="admin-form"><h3>تسجيل حضور</h3><div className="admin-form-grid">{select('studentId','الطالب',studentOptions)}{input('date','التاريخ','date')}{select('status','الحالة',[{value:'present',label:'حاضر'},{value:'late',label:'متأخر'},{value:'absent',label:'غائب'},{value:'excused',label:'بعذر'}])}</div>{area('note','ملاحظة',false)}<ActionButton>حفظ الحضور</ActionButton></form></div><div className="admin-list">{notificationRows.map(n=><div className="admin-list-row" key={n.id}><div><strong>{n.title}</strong><span>{n.userId?'إشعار مستخدم':'إشعار عام'} · {n.createdAt.toLocaleString('ar-IQ')}</span></div><DeleteButton resource="notification" id={n.id}/></div>)}</div></details>

      <details className="admin-panel"><summary><MapPin size={18}/> خريطة المدرسة</summary><div className="admin-panel-body"><form action={createLocationAction} className="admin-form"><h3>موقع/مرفق جديد</h3><div className="admin-form-grid">{input('nameAr','الاسم بالعربي')}{input('nameEn','الاسم بالإنكليزي')}{input('latitude','خط العرض','number',false)}{input('longitude','خط الطول','number',false)}{input('mapX','موضع X','number',false)}{input('mapY','موضع Y','number',false)}{input('icon','الأيقونة','text',false)}</div>{area('descriptionAr','الوصف بالعربي',false)}{area('descriptionEn','الوصف بالإنكليزي',false)}<ActionButton>إضافة الموقع</ActionButton></form><div className="admin-list">{locationRows.map(l=><div className="admin-list-row" key={l.id}><div><strong>{l.nameAr}</strong><span>{l.nameEn} · {l.latitude??'—'}, {l.longitude??'—'}</span></div><DeleteButton resource="location" id={l.id}/></div>)}</div></div></details>

      <details className="admin-panel"><summary><Settings2 size={18}/> إعدادات المنصة</summary><div className="admin-panel-body admin-two-col"><form action={updateSettingAction} className="admin-form"><h3>إعداد عام</h3><p className="admin-help">مفاتيح مفيدة: <code>portal_name_ar</code> و <code>portal_name_en</code> و <code>portal_tagline_ar</code> و <code>portal_tagline_en</code>.</p><div className="admin-form-grid">{input('key','مفتاح الإعداد')}{input('value','قيمة الإعداد')}</div><ActionButton>حفظ الإعداد</ActionButton></form><div className="admin-form"><h3>الإعدادات الحالية</h3>{settingsRows.length===0?<p className="admin-empty">لا توجد إعدادات مخصصة بعد.</p>:settingsRows.map(s=><div className="setting-row" key={s.key}><code>{s.key}</code><span>{JSON.stringify(s.value)}</span></div>)}</div></div></details>
    </div>
  </div>
}

function countRole(role:'student'|'teacher'|'admin'){ return requireDb().select({count:sql<number>`count(*)::int`}).from(users).where(eq(users.role,role)).then(r=>r[0]?.count??0) }
