import { and, desc, eq, or, sql } from 'drizzle-orm'
import { Bell, CalendarDays, Megaphone } from 'lucide-react'
import { requireDb } from '@/db'
import { announcements, notifications } from '@/db/schema'
import { getCurrentUser } from '@/lib/auth'
import { Localized } from '@/components/localized'
import { redirect } from 'next/navigation'
export const dynamic='force-dynamic'
export default async function Notifications(){const user=await getCurrentUser();if(!user)redirect('/login');const db=requireDb();const [ann,personal]=await Promise.all([db.select({id:announcements.id,titleAr:announcements.titleAr,titleEn:announcements.titleEn,bodyAr:announcements.bodyAr,bodyEn:announcements.bodyEn,publishedAt:announcements.publishedAt}).from(announcements).where(and(eq(announcements.published,true),or(eq(announcements.audience,'all'),eq(announcements.audience,'students'),and(eq(announcements.audience,'class'),eq(announcements.classId,user.classId??'00000000-0000-0000-0000-000000000000'))))).orderBy(desc(announcements.publishedAt)).limit(20),db.select({id:notifications.id,titleAr:notifications.titleAr,titleEn:notifications.titleEn,bodyAr:notifications.bodyAr,bodyEn:notifications.bodyEn,createdAt:notifications.createdAt}).from(notifications).where(or(eq(notifications.userId,user.id),sql`${notifications.userId} is null`)).orderBy(desc(notifications.createdAt)).limit(20)]);return <div className="page-card card"><div className="page-title-row"><div><h1 className="page-title"><Localized ar="آخر التبليغات" en="Latest alerts"/></h1><p className="page-subtitle"><Localized ar="الإعلانات والإشعارات القادمة من قاعدة المدرسة." en="Announcements and notifications from the school database."/></p></div><div className="stat-icon blue"><Bell size={20}/></div></div><div style={{marginTop:12}}>{[...ann.map(a=>({id:`a-${a.id}`,titleAr:a.titleAr,titleEn:a.titleEn,bodyAr:a.bodyAr,bodyEn:a.bodyEn,at:a.publishedAt,important:true})),...personal.map(n=>({id:`n-${n.id}`,titleAr:n.titleAr,titleEn:n.titleEn,bodyAr:n.bodyAr,bodyEn:n.bodyEn,at:n.createdAt,important:false}))].sort((a,b)=>(b.at?.getTime()??0)-(a.at?.getTime()??0)).map(x=><div className="notification-row" key={x.id}><div className="notice-icon">{x.important?<Megaphone size={17}/>:<CalendarDays size={17}/>}</div><div style={{flex:1}}><h3><Localized ar={x.titleAr} en={x.titleEn}/></h3><p><Localized ar={x.bodyAr} en={x.bodyEn}/></p><span style={{fontSize:8,color:'#a1a6b0'}}>{x.at?.toLocaleString('ar-IQ')}</span></div>{x.important&&<span className="pill red"><Localized ar="إعلان" en="Announcement"/></span>}</div>)}{ann.length===0&&personal.length===0&&<p className="admin-empty"><Localized ar="لا توجد تبليغات بعد." en="No alerts yet."/></p>}</div></div>}
