import { asc, eq, or, sql } from 'drizzle-orm'
import { CalendarDays, ChevronLeft, Clock3, MapPin } from 'lucide-react'
import { requireDb } from '@/db'
import { assignments, calendarEvents } from '@/db/schema'
import { getCurrentUser } from '@/lib/auth'
import { Localized } from '@/components/localized'
import { redirect } from 'next/navigation'
export const dynamic='force-dynamic'
export default async function CalendarPage(){const user=await getCurrentUser();if(!user)redirect('/login');const db=requireDb();const [events,work]=await Promise.all([db.select({id:calendarEvents.id,titleAr:calendarEvents.titleAr,titleEn:calendarEvents.titleEn,startsAt:calendarEvents.startsAt,location:calendarEvents.location}).from(calendarEvents).where(or(sql`${calendarEvents.classId} is null`,eq(calendarEvents.classId,user.classId??'00000000-0000-0000-0000-000000000000'))).orderBy(asc(calendarEvents.startsAt)).limit(40),db.select({id:assignments.id,titleAr:assignments.titleAr,titleEn:assignments.titleEn,dueAt:assignments.dueAt}).from(assignments).where(eq(assignments.classId,user.classId??'00000000-0000-0000-0000-000000000000')).orderBy(asc(assignments.dueAt)).limit(40)]);const all=[...events.map(e=>({id:e.id,titleAr:e.titleAr,titleEn:e.titleEn,at:e.startsAt,place:e.location,type:'event'})),...work.map(w=>({id:w.id,titleAr:w.titleAr,titleEn:w.titleEn,at:w.dueAt,place:'',type:'assignment'}))].sort((a,b)=>a.at.getTime()-b.at.getTime());return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">SCHOOL CALENDAR</span><h1><Localized ar="التقويم الدراسي" en="School calendar"/></h1><p><Localized ar="المواعيد الحقيقية المنشورة من الإدارة." en="Real dates published by the school administration."/></p></div><div className="calendar-month"><CalendarDays size={19}/><span><Localized ar="حسب بيانات المدرسة" en="School data"/></span></div></section><section className="calendar-layout"><div className="card calendar-card"><div className="calendar-empty-state"><CalendarDays size={38}/><h2><Localized ar="التقويم متصل بقاعدة البيانات" en="Calendar connected to the database"/></h2><p><Localized ar="يتم عرض الأحداث والواجبات المنشورة فقط." en="Only published school events and assignments are shown."/></p></div></div><div className="card events-card"><div className="section-heading"><div><h2><Localized ar="القادم" en="Upcoming"/></h2><p><Localized ar="الأحداث والواجبات القادمة" en="Upcoming events and assignments"/></p></div></div><div className="event-list">{all.length?all.map(e=><div className="event-row" key={`${e.type}-${e.id}`}><div className={`event-date ${e.type==='assignment'?'amber':'violet'}`}><strong>{e.at.toLocaleDateString('ar-IQ',{day:'2-digit'})}</strong><span>{e.at.toLocaleDateString('en-US',{month:'short'}).toUpperCase()}</span></div><div className="event-main"><strong><Localized ar={e.titleAr} en={e.titleEn}/></strong><div><span><Clock3 size={13}/>{e.at.toLocaleString('ar-IQ',{dateStyle:'medium',timeStyle:'short'})}</span>{e.place&&<span><MapPin size={13}/>{e.place}</span>}</div></div><ChevronLeft size={17} className="event-arrow"/></div>):<p className="admin-empty"><Localized ar="لا توجد أحداث أو واجبات منشورة." en="No published events or assignments."/></p>}</div></div></section></div>}
