import { and, count, eq } from 'drizzle-orm'
import { Mail, Phone, ShieldCheck, UserRound } from 'lucide-react'
import { requireDb } from '@/db'
import { attendanceRecords, classes, grades, assessments, users } from '@/db/schema'
import { getCurrentUser } from '@/lib/auth'
import { Localized } from '@/components/localized'
import { redirect } from 'next/navigation'
export const dynamic='force-dynamic'
export default async function Account(){const user=await getCurrentUser();if(!user)redirect('/login');const db=requireDb();const [classRow, gradeRows, attendance]=await Promise.all([user.classId?db.select().from(classes).where(eq(classes.id,user.classId)).limit(1):Promise.resolve([]),db.select({score:grades.score,max:assessments.maxScore}).from(grades).innerJoin(assessments,eq(assessments.id,grades.assessmentId)).where(and(eq(grades.studentId,user.id),eq(assessments.published,true))),db.select({status:attendanceRecords.status}).from(attendanceRecords).where(eq(attendanceRecords.studentId,user.id))]);const avg=gradeRows.length?gradeRows.reduce((a,g)=>a+(g.max?g.score/g.max*100:0),0)/gradeRows.length:0;const present=attendance.filter(a=>a.status==='present'||a.status==='late').length;const attendancePct=attendance.length?present/attendance.length*100:0;return <div className="page-card card"><div className="account-head"><div className="account-avatar">{user.fullNameAr.slice(0,1)}</div><div><h1>{user.fullNameAr}</h1><p>{user.studentNumber??user.email}{classRow[0]?` · ${classRow[0].nameAr}`:''}</p></div></div><div className="feature-grid"><div className="feature-card"><Mail size={17}/><h3><Localized ar="البريد المدرسي" en="School email"/></h3><p>{user.email}</p></div><div className="feature-card"><Phone size={17}/><h3><Localized ar="رقم التواصل" en="Contact number"/></h3><p>{user.phone??<Localized ar="غير مضاف" en="Not provided"/>}</p></div><div className="feature-card"><ShieldCheck size={17}/><h3><Localized ar="حالة الحساب" en="Account status"/></h3><p>{user.isActive?<Localized ar="فعال" en="Active"/>:<Localized ar="معطل" en="Disabled"/>}</p></div><div className="feature-card"><UserRound size={17}/><h3><Localized ar="الصف" en="Class"/></h3><p>{classRow[0]?.nameAr??<Localized ar="غير محدد" en="Not assigned"/>}</p></div></div><div style={{marginTop:20}}><div className="stat-line"><span><Localized ar="المعدل العام" en="Overall average"/></span><strong>{avg.toFixed(1)}%</strong></div><div className="stat-line"><span><Localized ar="الحضور" en="Attendance"/></span><strong>{attendancePct.toFixed(1)}%</strong></div><div className="stat-line"><span><Localized ar="التقييمات المسجلة" en="Recorded assessments"/></span><strong>{gradeRows.length}</strong></div></div></div>}
