import Link from 'next/link'
import { and, desc, eq, or, sql } from 'drizzle-orm'
import { ArrowUpLeft, Bell, BookOpen, CalendarDays, CheckCircle2, ChevronLeft, Clock3, FileCheck2, GraduationCap, LogIn, TrendingUp } from 'lucide-react'
import { requireDb } from '@/db'
import { announcements, assessments, assignments, calendarEvents, files, grades, subjects, siteSettings, users } from '@/db/schema'
import { getCurrentUser } from '@/lib/auth'
import { Localized } from '@/components/localized'
import { SectionHeader, Pill, MiniBar } from '@/components/ui'

export const dynamic='force-dynamic'

export default async function HomePage(){
  const user=await getCurrentUser()
  if(!user) return <div className="page-stack"><section className="hero-card"><div className="hero-content"><Pill tone="light">School Pulse</Pill><h1><Localized ar="مرحبًا بك في بوابة المدرسة" en="Welcome to the school portal"/></h1><p><Localized ar="سجّل الدخول لعرض درجاتك، واجباتك، تقويمك، وتبليغاتك الشخصية." en="Sign in to see your grades, assignments, calendar, and personal alerts."/></p><div className="hero-actions"><Link href="/login" className="button button-light"><LogIn size={17}/><Localized ar="تسجيل الدخول" en="Sign in"/></Link><Link href="/rules" className="button button-ghost-light"><Localized ar="قواعد المنصة" en="Platform rules"/><ArrowUpLeft size={17}/></Link></div></div></section></div>
  const db=requireDb()
  const [gradeRows, announcementRows, eventRows, assignmentRows, fileRows, settingRows]=await Promise.all([
    db.select({score:grades.score,maxScore:assessments.maxScore,subject:subjects.nameAr,subjectEn:subjects.nameEn,examOrder:assessments.examOrder}).from(grades).innerJoin(assessments,eq(assessments.id,grades.assessmentId)).innerJoin(subjects,eq(subjects.id,assessments.subjectId)).where(and(eq(grades.studentId,user.id),eq(assessments.published,true))).orderBy(desc(grades.gradedAt)).limit(20),
    db.select({id:announcements.id,titleAr:announcements.titleAr,titleEn:announcements.titleEn,bodyAr:announcements.bodyAr,bodyEn:announcements.bodyEn,publishedAt:announcements.publishedAt}).from(announcements).where(and(eq(announcements.published,true),or(eq(announcements.audience,'all'),eq(announcements.audience,'students'),and(eq(announcements.audience,'class'),eq(announcements.classId,user.classId??'00000000-0000-0000-0000-000000000000'))))).orderBy(desc(announcements.publishedAt)).limit(4),
    db.select({id:calendarEvents.id,titleAr:calendarEvents.titleAr,titleEn:calendarEvents.titleEn,startsAt:calendarEvents.startsAt,location:calendarEvents.location}).from(calendarEvents).where(or(sql`${calendarEvents.classId} is null`,eq(calendarEvents.classId,user.classId??'00000000-0000-0000-0000-000000000000'))).orderBy(calendarEvents.startsAt).limit(4),
    db.select({id:assignments.id,titleAr:assignments.titleAr,titleEn:assignments.titleEn,dueAt:assignments.dueAt,subjectAr:subjects.nameAr,subjectEn:subjects.nameEn}).from(assignments).innerJoin(subjects,eq(subjects.id,assignments.subjectId)).where(and(eq(assignments.published,true),or(eq(assignments.classId,user.classId??'00000000-0000-0000-0000-000000000000'),eq(assignments.classId,user.classId??'00000000-0000-0000-0000-000000000000')))).orderBy(assignments.dueAt).limit(4),
    db.select({id:files.id,name:files.name,createdAt:files.createdAt}).from(files).where(eq(files.ownerId,user.id)).orderBy(desc(files.createdAt)).limit(4),
    db.select().from(siteSettings).where(or(eq(siteSettings.key,'portal_name_ar'),eq(siteSettings.key,'portal_name_en'),eq(siteSettings.key,'portal_tagline_ar'),eq(siteSettings.key,'portal_tagline_en'))),
  ])
  const settings=new Map(settingRows.map(x=>[x.key, String((x.value as any)?.value??'')]))
  const portalNameAr=settings.get('portal_name_ar')||'بوابة المدرسة', portalNameEn=settings.get('portal_name_en')||'School Portal'
  const total=gradeRows.reduce((a,g)=>a+(g.maxScore?g.score/g.maxScore*100:0),0), avg=gradeRows.length?total/gradeRows.length:0
  const subjectMap=new Map<string,{ar:string;en:string;score:number;count:number}>(); for(const g of gradeRows){const k=g.subject;if(!subjectMap.has(k)) subjectMap.set(k,{ar:k,en:g.subjectEn,score:0,count:0});const x=subjectMap.get(k)!;x.score += g.maxScore?g.score/g.maxScore*100:0;x.count++}
  const subjectsPerf=[...subjectMap.values()].map(x=>({...x,score:Math.round(x.score/x.count)})).slice(0,5)
  return <div className="page-stack">
    <section className="hero-card"><div className="hero-content"><Pill tone="light"><Localized ar={portalNameAr} en={portalNameEn}/></Pill><h1><Localized ar={`أهلًا، ${user.fullNameAr}`} en={`Welcome, ${user.fullNameEn}`}/></h1><p><Localized ar="واجهة مركزة لما يهمك الآن من بيانات حقيقية محفوظة في قاعدة المدرسة." en="A focused view of the real data stored in your school database."/></p><div className="hero-actions"><Link href="/calendar" className="button button-light"><CalendarDays size={17}/><Localized ar="فتح التقويم" en="Open calendar"/></Link><Link href="/grades" className="button button-ghost-light"><Localized ar="عرض الدرجات" en="View grades"/><ArrowUpLeft size={17}/></Link></div></div><div className="hero-side"><div className="hero-stat-label"><Localized ar="المعدل الحالي" en="Current average"/></div><div className="hero-stat">{avg.toFixed(1)}<span>%</span></div><div className="hero-stat-foot"><TrendingUp size={15}/><Localized ar="محسوب من الدرجات المنشورة" en="Calculated from published grades"/></div></div></section>
    <section className="stats-grid compact-stats"><div className="stat-card tone-blue"><div className="stat-icon"><GraduationCap size={19}/></div><span><Localized ar="المعدل العام" en="Overall average"/></span><strong>{avg.toFixed(1)}%</strong></div><div className="stat-card tone-purple"><div className="stat-icon"><BookOpen size={19}/></div><span><Localized ar="المواد" en="Subjects"/></span><strong>{subjectsPerf.length}</strong></div><div className="stat-card tone-orange"><div className="stat-icon"><Clock3 size={19}/></div><span><Localized ar="الواجبات القادمة" en="Upcoming assignments"/></span><strong>{assignmentRows.length}</strong></div></section>
    <section className="today-grid"><div className="card today-card"><div className="section-header"><div><h2><Localized ar="القادم اليوم" en="Up next"/></h2><p><Localized ar="أقرب أحداث التقويم" en="Your next calendar events"/></p></div><Link href="/calendar"><Localized ar="التقويم الكامل" en="Full calendar"/> ←</Link></div><div className="today-list">{eventRows.length?eventRows.map(e=><div className="today-row" key={e.id}><div className="today-time">{e.startsAt.toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'})}</div><div className="today-copy"><strong><Localized ar={e.titleAr} en={e.titleEn}/></strong><span>{e.location??<Localized ar="بدون موقع" en="No location"/>}</span></div><span className="today-state"><Localized ar="موعد" en="Event"/></span></div>):<p className="admin-empty"><Localized ar="لا توجد مواعيد قادمة." en="No upcoming events."/></p>}</div></div>
      <div className="card today-card"><div className="section-header"><div><h2><Localized ar="الواجبات" en="Assignments"/></h2><p><Localized ar="المهام المنشورة لصفك" en="Published work for your class"/></p></div><Link href="/calendar"><Localized ar="التقويم" en="Calendar"/> ←</Link></div><div className="assignment-list">{assignmentRows.length?assignmentRows.map(a=><div className="assignment-row" key={a.id}><div className="assignment-status open"><CheckCircle2 size={16}/></div><div className="assignment-copy"><strong><Localized ar={a.titleAr} en={a.titleEn}/></strong><span>{a.subjectAr} · {a.dueAt.toLocaleString('ar-IQ')}</span></div><span className="assignment-pill open"><Localized ar="مطلوب" en="Due"/></span></div>):<p className="admin-empty"><Localized ar="لا توجد واجبات منشورة." en="No published assignments."/></p>}</div></div></section>
    <section className="dashboard-grid calm-grid"><div className="card chart-card"><SectionHeader title="" subtitle="" href="/grades" link=""/><div className="section-header"><div><h2><Localized ar="أداء المواد" en="Subject performance"/></h2><p><Localized ar="آخر متوسط محسوب من بياناتك" en="Latest averages calculated from your data"/></p></div><Link href="/grades"><Localized ar="كل الدرجات" en="All grades"/> ←</Link></div><div className="subject-list">{subjectsPerf.length?subjectsPerf.map(s=><div key={s.ar} className="subject-row"><div className="subject-main"><span className="subject-dot blue"/><div><strong><Localized ar={s.ar} en={s.en}/></strong><small><Localized ar="متوسط المادة" en="Subject average"/></small></div></div><div className="subject-meter"><MiniBar value={s.score}/></div><div className="subject-score"><strong>{s.score}</strong><span>%</span></div></div>):<p className="admin-empty"><Localized ar="ستظهر المواد بعد إدخال الدرجات ونشرها." en="Subjects appear after grades are entered and published."/></p>}</div></div>
      <div className="card schedule-card"><div className="section-header"><div><h2><Localized ar="آخر التبليغات" en="Latest alerts"/></h2><p><Localized ar="الإعلانات المنشورة لك" en="Published announcements for you"/></p></div><Link href="/notifications"><Localized ar="الكل" en="All"/> ←</Link></div><div className="event-list compact">{announcementRows.length?announcementRows.map(a=><Link href="/notifications" className="event-row" key={a.id}><div className="event-date violet"><Bell size={17}/></div><div className="event-main"><strong><Localized ar={a.titleAr} en={a.titleEn}/></strong><div><span>{a.publishedAt?.toLocaleDateString('ar-IQ')??''}</span></div></div><ChevronLeft size={16} className="event-arrow"/></Link>):<p className="admin-empty"><Localized ar="لا توجد تبليغات منشورة." en="No published alerts."/></p>}</div></div></section>
    <section className="card activity-card"><div className="section-header"><div><h2><Localized ar="النشاط الأخير" en="Recent activity"/></h2><p><Localized ar="آخر تحديثات حسابك المحفوظة" en="Recent changes saved for your account"/></p></div></div><div className="activity-timeline">{[...gradeRows.slice(0,2).map(g=>({key:`g-${g.subject}-${g.examOrder}`,icon:CheckCircle2,titleAr:`تم تحديث درجة ${g.subject}`,titleEn:`A grade was updated for ${g.subjectEn}`,detailAr:`النتيجة ${g.score}/${g.maxScore}`,detailEn:`Score ${g.score}/${g.maxScore}`})),...fileRows.slice(0,2).map(f=>({key:`f-${f.id}`,icon:FileCheck2,titleAr:'تم حفظ ملف في حسابك',titleEn:'A file was saved to your account',detailAr:f.name,detailEn:f.name}))].length?null:null}{gradeRows.length===0&&fileRows.length===0?<p className="admin-empty"><Localized ar="لا توجد نشاطات بعد." en="No activity yet."/></p>:[...gradeRows.slice(0,2).map(g=>({key:`g-${g.subject}-${g.examOrder}`,icon:CheckCircle2,titleAr:`تم تحديث درجة ${g.subject}`,titleEn:`A grade was updated for ${g.subjectEn}`,detailAr:`النتيجة ${g.score}/${g.maxScore}`,detailEn:`Score ${g.score}/${g.maxScore}`})),...fileRows.slice(0,2).map(f=>({key:`f-${f.id}`,icon:FileCheck2,titleAr:'تم حفظ ملف في حسابك',titleEn:'A file was saved to your account',detailAr:f.name,detailEn:f.name}))].map(item=>{const I=item.icon;return <div className="activity-item" key={item.key}><div className="activity-icon blue"><I size={16}/></div><div className="activity-line"/><div className="activity-copy"><div className="activity-meta"><strong><Localized ar={item.titleAr} en={item.titleEn}/></strong></div><p><Localized ar={item.detailAr} en={item.detailEn}/></p></div></div>})}</div></section>
  </div>
}
