import { desc, eq, or } from 'drizzle-orm'
import { MessageCircle, UserPlus } from 'lucide-react'
import { requireDb } from '@/db'
import { messageRequests, users } from '@/db/schema'
import { getCurrentUser } from '@/lib/auth'
import { Localized } from '@/components/localized'
import { redirect } from 'next/navigation'
export const dynamic='force-dynamic'
export default async function Messages(){const user=await getCurrentUser();if(!user)redirect('/login');const rows=await requireDb().select({id:messageRequests.id,body:messageRequests.body,subject:messageRequests.subject,status:messageRequests.status,createdAt:messageRequests.createdAt,sender:users.fullNameAr,senderEn:users.fullNameEn}).from(messageRequests).innerJoin(users,eq(users.id,messageRequests.senderId)).where(or(eq(messageRequests.recipientId,user.id),eq(messageRequests.senderId,user.id))).orderBy(desc(messageRequests.createdAt)).limit(30);return <div className="page-card card"><div className="page-title-row"><div><h1 className="page-title"><Localized ar="طلبات المراسلة" en="Message requests"/></h1><p className="page-subtitle"><Localized ar="الطلبات والرسائل المحفوظة في قاعدة البيانات." en="Requests and messages stored in the database."/></p></div><div className="stat-icon purple"><MessageCircle size={20}/></div></div><div className="messages" style={{marginTop:15}}>{rows.length?rows.map(r=><div className="message-item" key={r.id}><span className="avatar purple">{r.sender.slice(0,1)}</span><div style={{flex:1}}><strong style={{fontSize:10}}><Localized ar={r.sender} en={r.senderEn}/></strong><p style={{margin:'3px 0',fontSize:8,color:'#7a8290'}}>{r.subject??r.body}</p><span className="pill slate">{r.status}</span></div></div>):<div className="card" style={{padding:18,boxShadow:'none'}}><UserPlus size={22}/><h3 style={{fontSize:13,margin:'11px 0 4px'}}><Localized ar="لا توجد طلبات مراسلة" en="No message requests"/></h3><p style={{fontSize:9,color:'#7b8391',lineHeight:1.8}}><Localized ar="ستظهر هنا الطلبات التي تصل إلى حسابك." en="Requests sent to your account will appear here."/></p></div>}</div></div>}
