import { loginAction } from './actions'
import Link from 'next/link'
import { Chrome, ShieldCheck } from 'lucide-react'

export default async function Login({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams
  const message = error === 'missing' ? 'أدخل البريد وكلمة المرور.' : error === 'invalid' ? 'بيانات الدخول غير صحيحة.' : error === 'rate_limited' ? 'تم إيقاف الطلبات مؤقتًا بسبب معدل مرتفع.' : error === 'password_locked' ? 'تم قفل محاولات كلمة المرور لمدة 15 دقيقة بعد محاولات فاشلة متكررة.' : error === 'google_not_configured' ? 'Google Auth غير مهيأ بعد. أضف مفاتيح Google إلى البيئة.' : error === 'google_cancelled' ? 'تم إلغاء تسجيل Google.' : error === 'google_state' ? 'انتهت جلسة Google. ابدأ من جديد.' : error === 'google_profile' ? 'تعذر التحقق من حساب Google.' : error === 'admin_google_blocked' ? 'حساب الإدارة يستخدم البريد وكلمة المرور ثم TOTP.' : error === 'registration_expired' ? 'انتهت جلسة التسجيل. ابدأ من Google من جديد.' : error === 'account_inactive' ? 'هذا الحساب غير مفعّل حاليًا. راجع إدارة المدرسة.' : null
  return <main className="auth-page"><div className="auth-card card"><div className="auth-security-icon"><ShieldCheck size={22}/></div><span className="eyebrow">SCHOOL PULSE</span><h1>الدخول إلى المنصة</h1><p>الطلاب والمدرسون يستخدمون Google. حسابات الإدارة تدخل بالبريد وكلمة المرور ثم TOTP.</p>{message && <div className="form-error">{message}</div>}<Link href="/api/auth/google" className="google-login-button"><Chrome size={18}/>المتابعة باستخدام Google</Link><div className="auth-divider"><span>دخول الإدارة</span></div><form action={loginAction} className="form-stack"><label>البريد الإلكتروني<input name="email" type="email" autoComplete="email" required /></label><label>كلمة المرور<input name="password" type="password" autoComplete="current-password" required /></label><button className="button button-primary" type="submit">دخول الإدارة</button></form><p className="registration-login-note">طالب جديد؟ ابدأ من Google، ثم املأ بيانات التسجيل وستصل للإدارة للموافقة.</p><Link href="/" className="auth-back">العودة للبوابة</Link></div></main>
}
